---
title: "Compilado investigacion estadística"
author: "Ricardo Márquez Salazar"
bibliography: referencias.bib
csl: apa.csl
lang: es
format:
  html:
    toc: true
---

\newpage

## Citas útiles 

### SPSS en R

* Debes saber que Spss en R no debería trabajar usando texto, sino todo en números, es por eso que etiquetarlo se hace tan necesario. Variables cuantitativas: numéricas y ordinales, incluso categoricas deben ser números con etiquetas.

* Para tablas usar apply_labels() para modelamiento y ggplot usar as.factor(). Se deben tener 2 bases de datos [@spsslabels_04].

```r
# Creamos una versión "lista para modelos"
datos_modelo <- encuesta %>% 
  mutate(across(where(expss::is.labelled), as.factor))

# Ahora la regresión es más limpia
modelo_2 <- glm(satisfaccion ~ ingresos + region, 
                data = datos_modelo, 
                family = "binomial")

summary(modelo_2)
```

* Para aprender sobre etiquetas Spss en R: @spsslabels_01.

Siempre usar al empezar:

```cmd
library(haven)
library(expss)
spss_data = haven::read_spss("spss_file.sav")
# add missing 'labelled' class
spss_data = add_labelled_class(spss_data)
```

* Para etiquetar corrrectamente, hacer tablas y gráficar usar @spsslabels_02.

Recuerda usar factor para gráficar en ggplot.

```r
library(ggplot2)
library(expss)
# Convertimos las etiquetas de valor en factores de R
# Esto hace que el "1" se convierta en "Hombre" visualmente
data_para_grafico = spss_data %>% 
    mutate(
        genero_factor = as_factor(genero),
        satisfaccion_factor = as_factor(satisfaccion)
    )
```

* Para más ejemplos de label con spss revisar la documentación de expss @spsslabels_03.

### Quarto

* Según @gemini260226_quarto01, este es el formato que debo seguir para organizar mis archivos:

## Código R

* across en dplyr

```r
lm(dist ~ speed, cars)
```

## Codigo Github

\newpage

## Videos de Youtube

### Citas para Programación de Sistemas

* Motorola estuvo centrada en el hardware, variandolo y basando su modelo de negocios en el exterior del dispositivo, con la llegada del Iphone el paradigma cambio y lo más importante se volvío el ecosistema (software y su logística) y ahí es donde está el valor agregado. Motorola lo entendío y se enfocó en vigilancia de nicho (radio y camaras de policía,sistema 911, análisis de evidencia digital y almacenamiento, seguridad pública)[@informek_01].

### Referencias
::: {#refs}
:::
